upgrade eslint to version 8, add stricter rules, and add templates for next and angular
CodingSans/eslint-config-codingsans pull request #11
Opened 2022-10-25 15:21 UTC by GAlexIHU

Possible TODO:
- next and angular templates are not super details
- still have to try out locally on different projects to see how it feels

2022-11-04 13:43 UTC, latotty requested changes

2022-11-04 13:43 UTC, latotty commented on README.md
>  ## ESLINT Version
This config created for eslint 8

2022-11-04 13:43 UTC, latotty commented on angular-recommended.js
> +  extends: ['./ts-recommended.js', ''],
`extends: ['./ts-recommended.js'],`

2022-11-04 13:43 UTC, latotty commented on package.json
> +    "node": "^14.18.0 || >=16.0.0"
node 15?

2022-11-04 13:43 UTC, latotty commented on tsconfig.base.json
> +    "target": "ESNext",
that is too wide, fix it to node14 (ES2020)

2022-11-23 13:42 UTC, GAlexIHU commented on package.json
> +    "node": "^14.18.0 || >=16.0.0"
https://eslint.org/docs/latest/user-guide/migrating-to-8.0.0#drop-old-node

2022-11-23 14:59 UTC, merged